### ISSUE TITLE
rc-util依赖版本有误

### ISSUE THREAD

**Issue by yhls7** [react-component/virtual-list#170]
rc-virtual-list >=3.4.3下src/List使用rc-util的useLayoutEffect替换react默认钩子，该方法是rc-util >=5.15.0版本加入的。但rc-virtual-list 依赖的rc-util版本为"rc-util": "^5.0.7"，若安装的rc-util低于5.15.0则会导致打包错误

**Comment by yoyo837** [comment]
项目里不需要直接依赖rc-util，如果从antd那边使用的，删除node_modules和lock文件全新安装即可。

**Comment by yoyo837** [comment]
仍有问题，请再反馈。

**Comment by lzy2014love** [comment]
> rc-virtual-list >=3.4.3下src/List使用rc-util的useLayoutEffect替换react默认钩子，该方法是rc-util >=5.15.0版本加入的。但rc-virtual-list 依赖的rc-util版本为"rc-util": "^5.0.7"，若安装的rc-util低于5.15.0则会导致打包错误

我也是同样的问题。为避免这样的情况发生，rc-virtual-list 依赖的rc-util版本改为5.15.0以上。否则删掉 lock文件会导致其他依赖的自动更新的新问题。

**Comment by yoyo837** [comment]
来个PR？

**Comment by zjjjjjjjjjjd** [comment]
相同问题，分析一下：
主要是之前，其他依赖安装过**rc-util@^5.0.7**  这东西，且当时最新的在5.15.0以下，导致我自己添加rc-virtual-list的时候，相同的**rc-util@^5.0.7**被lock文件锁在了旧版本，然鹅，最新的rc-virtual-list应该需要依赖5.15.0以上的版本才能正常运行
![image](https://user-images.githubusercontent.com/32830366/160037644-71dfe6b7-bc8d-4adb-ac89-414faeee1a5b.png)
最好是升级rc-virtual-list内的rc-util版本，或者自己手动把lock文件里的5.0.7依赖先删掉重新安装

**Comment by lzy2014love** [comment]
> 相同问题，分析一下： 主要是之前，其他依赖安装过**rc-util@^5.0.7** 这东西，且当时最新的在5.15.0以下，导致我自己添加rc-virtual-list的时候，相同的**rc-util@^5.0.7**被lock文件锁在了旧版本，然鹅，最新的rc-virtual-list应该需要依赖5.15.0以上的版本才能正常运行 ![image](https://user-images.githubusercontent.com/32830366/160037644-71dfe6b7-bc8d-4adb-ac89-414faeee1a5b.png) 最好是升级rc-virtual-list内的rc-util版本，或者自己手动把lock文件里的5.0.7依赖先删掉重新安装

前天提了个pr，现在virtual-list的rc-util版本已经升到5.15以上了
