### ISSUE TITLE
控制台有warning提示，ref使用不正确

### ISSUE THREAD

**Issue by qianchengjie** [react-component/virtual-list#195]
```
Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()?

Check the render method of `Item`.
```

**Comment by dario-fiore** [comment]
Has anyone been keeping up with this discussion?

**Comment by yoyo837** [comment]
Could you please provide a reproduction and submit the issue to `antd`?

**Comment by qianchengjie** [comment]
https://github.com/react-component/virtual-list/issues/195#issuecomment-1953557167

I created a new [issue](https://github.com/ant-design/ant-design/issues/47496) in antd

**Comment by qianchengjie** [comment]
https://github.com/ant-design/ant-design/issues/47496#issuecomment-1953584557
