### ISSUE TITLE
rc-virtual-list 3.10.0  problems with the last update

### ISSUE THREAD

**Issue by RafaelCss** [react-component/virtual-list#218]
`#13 8.176 ./node_modules/rc-virtual-list/lib/List.d.ts:5:15
#13 8.176 Type error: ',' expected.
#13 8.176
#13 8.176   3 | import type { ScrollBarDirectionType } from './ScrollBar';
#13 8.176   4 | import type { RenderFunc, ExtraRenderInfo } from './interface';
#13 8.176 > 5 | import { type ScrollPos, type ScrollTarget } from './hooks/useScrollTo';
#13 8.176     |               ^
#13 8.176   6 | export interface ScrollInfo {
#13 8.176   7 |     x: number;
#13 8.176   8 |     y: number;
#13 8.204 npm notice`

Hello, today after the update I've been suffering from this problem only when the application builds, I don't use the lib directly as it depended on antd if I'm not mistaken. Does anyone know how to fix?

**Comment by irishkungfu** [comment]
We are running into the exact same error when running on Github Actions. Any assistance would be great.

```
#19 [15/16] RUN yarn workspace shared-library compile
#19 6.375 ../../node_modules/rc-virtual-list/lib/List.d.ts(5,15): error TS1005: ',' expected.
#19 6.377 ../../node_modules/rc-virtual-list/lib/List.d.ts(5,31): error TS1005: ',' expected.
#19 ERROR: process "/bin/sh -c yarn workspace shared-library compile" did not complete successfully: exit code: 2
```

**Comment by zombieJ** [comment]
It's validate TS definition, seems you should upgrade TS version instead. And for #219 , I'm OK to merge that.

**Comment by RafaelCss** [comment]
I updated the TS version to 4.9.5 it worked

**Comment by RafaelCss** [comment]
yes, we were using 4.3.5
