### ISSUE TITLE
antd- Dropdown会导致侧边滚动条不生效

### ISSUE THREAD

**Issue by zengshoulong66** [react-component/virtual-list#225]
--- antd的下拉菜单中使用导致侧边滚动条失效, 貌似侧边滚动条件监听未生效.
![image](https://github.com/react-component/virtual-list/assets/48672606/5bab6530-3ba1-497e-a0a2-935dc70e6b47)

**Comment by yoyo837** [comment]
带复现上antd创建个issue?
