### ISSUE TITLE
Select 组件 Option元素个数超出限定的高度 没有出现滚动条

### ISSUE THREAD

**Issue by Snake-Master** [react-component/virtual-list#227]
antd版本： 4.24.14

问题： 使用普通的Select 组件，当元素个数超过高度需要滚动时，没有出现滚动条。
![image](https://github.com/react-component/virtual-list/assets/6490250/f9df4fdf-6284-4102-a93c-c0c38afd885c)

把rc-virtual-list 版本降低到3.5.3及以前， 可以出现。

**Comment by Promisezhangbo** [comment]
我也出现了这个问题，现在直接降到了3.5.1 就可以了，请问一下更高的版本后期能否支持

**Comment by JackClown** [comment]
+1

**Comment by yoyo837** [comment]
Fixed in https://github.com/react-component/virtual-list/releases/tag/v3.11.5
