### ISSUE TITLE
Error: `NaN` is an invalid value for the `marginLeft` css style property.

### ISSUE THREAD

**Issue by NameWjp** [react-component/virtual-list#261]
复现地址：[codesandbox](https://codesandbox.io/p/sandbox/xu-ni-lie-biao-antd-5-15-3-forked-cpjj9l?file=%2Fdemo.tsx%3A10%2C11&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clu6nj6sz0006356h70zk1ngo%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clu6nj6sz0002356h5myr0szw%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clu6nj6sz0003356hmj2gt0ak%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clu6nj6sz0005356hsejn79wk%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clu6nj6sz0002356h5myr0szw%2522%253A%257B%2522id%2522%253A%2522clu6nj6sz0002356h5myr0szw%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cluavyy9z0002356heptgsj6m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A11%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A11%257D%255D%252C%2522filepath%2522%253A%2522%252Fdemo.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cluavyy9z0002356heptgsj6m%2522%257D%252C%2522clu6nj6sz0005356hsejn79wk%2522%253A%257B%2522id%2522%253A%2522clu6nj6sz0005356hsejn79wk%2522%252C%2522activeTabId%2522%253A%2522cluavxmf00016356hunzcdfey%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522cluavxmf00016356hunzcdfey%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clu6nj6sz0003356hmj2gt0ak%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clu6nj6sz0003356hmj2gt0ak%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

复现步骤：
1. 鼠标放到虚拟滚动列表里
2. 按住 shift 滚动滚轮
3. 浏览器报错 Warning: `NaN` is an invalid value for the `marginLeft` css style property.

![image](https://github.com/react-component/virtual-list/assets/32758131/0f69652b-c2bb-42dd-849d-fabadcce4053)

**Comment by yoyo837** [comment]
Fixed in #262
