### ISSUE TITLE
List.js "Not find index item. Please report this since it is a bug."

### ISSUE THREAD

**Issue by stefanspicer** [react-component/virtual-list#27]
I recently installed https://github.com/ukrbublik/react-awesome-query-builder/, which is using https://github.com/ant-design/ant-design/ and one of those 2 is using your rc-virtual-list. Can you give me more insight into this "Not find index item." Is this related to the list being removed? https://github.com/react-component/virtual-list/commit/28c069da8766f681eb1779f7626ee540b9f24197

Any info you can provide would be helpful. Thanks.

Here is my stack trace if it helps. Sorry there are no filenames.

Not find index item. Please report this since it is a bug. 
    at List 
    at OptionList 
    at div
    at div
    at PopupInner 
    at Align 
    at CSSMotion 
    at div
    at Popup 
    at Portal 
    at Trigger 
    at SelectTrigger 
    at div
    at Select 
    at Select 
    at Select 
    at FieldSelect 
    at Field 
    at div
    at Col 
    at FieldWrapper 
    at div
    at Rule 
    at div
    at Draggable 
    at div
    at RuleContainer 
    at ConnectedRuleContainer 
    at Item 
    at div
    at Group 
    at div
    at Draggable 
    at div
    at GroupContainer 
    at ConnectedGroupContainer 
    at Item 
    at Builder 
    at SortableContainer 
    at ConnectedSortableContainer 
    at div
    at div
    at Query 
    at ConnectedQuery 
    at Provider 
    at LocaleProvider 
    at SizeContextProvider 
    at LocaleReceiver 
    at ConfigProvider 
    at Provider 
    at renderProvider
    at QueryContainer 
    at div
    at PeopleQueryBuilder 
    at App

**Comment by stefanspicer** [comment]
Hi, are you able to help me with this at all?

**Comment by zombieJ** [comment]
After refactoring, this issue has gone. Thanks for report.
