### ISSUE TITLE
React 17: Cannot read property 'removeEventListener' of null

### ISSUE THREAD

**Issue by damiangreen** [react-component/virtual-list#51]
This error is thrown "React 17: Cannot read property 'removeEventListener' of null" when using React 17, unmounting

```
  217 | React.useEffect(function () {
  218 |   componentRef.current.addEventListener('wheel', onRawWheel);
  219 |   return function () {
> 220 |     componentRef.current.removeEventListener('wheel', onRawWheel);
      | ^  221 |   };
  222 | }, [inVirtual]); // ================================= Ref ==================================
  223 | 
```

**Comment by Thanaen** [comment]
It happens to me as well, but not systematically.
I will try to make a codesandbox on my free time to easily reproduce this bug.

Package version: 3.0.7
Browser: Microsoft Edge 86.0.615.3

**Comment by zombieJ** [comment]
Since React 17 is still in rc version. I may not try to dig it out util official mainer version released.

**Comment by Thanaen** [comment]
Today it happened to me again with React 16 this time. Shall I open a new issue for this ?

**Comment by zombieJ** [comment]
Sure. Please ~~

**Comment by Thanaen** [comment]
After several tests, it turns out that we were still running React 17 (the folder node_modules must not have supported the downgrade of the React version).
So, until proven otherwise, the bug does not occur under React 16. ✌

**Comment by zombieJ** [comment]
Thanks for your feedback : )

**Comment by damiangreen** [comment]
React 17 is now released! :)

**Comment by damiangreen** [comment]
IS it worth fixing / re-opening this case?

**Comment by zombieJ** [comment]
This is already fixed in https://github.com/react-component/virtual-list/pull/67
